import { ErrorMessage, Formik } from "formik";
import { NextPage } from "next";
import { withUrqlClient } from "next-urql";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import InputField from "../../components/InputField";
import NavBar from "../../components/NavBar";
import {
  useChangePasswordMutation,
  useLoginMutation,
} from "../../src/generated/graphql";
import { toErrorMap } from "../../src/helpers/toErrorMap";
import { createUrqlClient } from "../../src/utils/createUrqlClient";

interface LoginProps {}

const ChangePassword: NextPage = ({}) => {
  const [, change] = useChangePasswordMutation();
  const router = useRouter();

  const { token } = router.query;

  return (
    <main className="">
      {/* <pre>{token}</pre> */}
      <Head>
        <title>Change Password</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar pageProps />
      <div className={styles.screen}>
        <div className="p-8">
          <div className={styles.container}>
            <div className={styles.formContainer}>
              <h1 className="text-2xl font-semibold text-gray-900">
                Hello! 👋
              </h1>
              <Formik
                initialValues={{ password: "", token: "" }}
                onSubmit={async (values, { setSubmitting, setErrors }) => {
                  const response = await change({
                    token: token as string,
                    password: values.password,
                  });
                  if (response.data?.changePassword.errors) {
                    setErrors(toErrorMap(response.data.changePassword.errors));
                  } else {
                    router.push("/");
                  }
                  setSubmitting(false);
                }}
              >
                {({ handleSubmit, isSubmitting }) => (
                  <form className="mt-6" onSubmit={handleSubmit}>
                    <div className="relative mt-10">
                      <InputField
                        label="Password"
                        name="password"
                        type="password"
                        className={styles.inputField}
                        placeholder="password"
                      />
                    </div>
                    <ErrorMessage
                      component="span"
                      className="text-red-500"
                      name="token"
                    />

                    <input
                      type="submit"
                      value={isSubmitting ? "Loading" : "Change"}
                      disabled={isSubmitting}
                      className={styles.button}
                    />
                  </form>
                )}
              </Formik>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

const styles = {
  container: "w-80 bg-white rounded-3xl mx-auto overflow-hidden shadow-xl",
  formContainer: "px-10 pt-4 pb-8 bg-white rounded-tr-3xl",
  inputField:
    "peer h-10 w-full border-b-2 border-gray-300 text-gray-900 placeholder-transparent focus:outline-none focus:border-rose-600",
  button:
    "mt-16 px-4 py-2 rounded bg-rose-500 hover:bg-rose-400 text-white font-semibold text-center block w-full focus:outline-none focus:ring focus:ring-offset-2 focus:ring-rose-500 focus:ring-opacity-80 cursor-pointer",
  screen: "min-h-screen bg-rose-100 flex justify-center items-center",
};

export default withUrqlClient(createUrqlClient)(ChangePassword);
