import { withUrqlClient } from "next-urql";
import Head from "next/head";
import NavBar from "../components/NavBar";
import { usePostsQuery } from "../src/generated/graphql";
import { createUrqlClient } from "../src/utils/createUrqlClient";
import styles from "../styles/Home.module.css";

function Home() {
  const [{ data }] = usePostsQuery();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar pageProps />

      <main className={styles.main}>
        <h2 className="text-3xl font-bold underline">Hello World!</h2>

        <div>
          {!data ? (
            <div>load...</div>
          ) : (
            data.getPosts.map((post) => <h1 key={post.id}>{post.title}</h1>)
          )}
        </div>
      </main>
    </div>
  );
}

export default withUrqlClient(createUrqlClient, { ssr: true })(Home);
